# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 20

[[main]]
  name = "Courses"
  url = "courses/"
  weight = 30

[[main]]
  name = "Sharing"
  url = "sharing/"
  weight = 40

[[main]]
  name = "CV"
  url = "files/cv.pdf"
  weight = 50

